twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/public/assets/images': img

when@test:
    twig:
        strict_variables: true
